# Generated by Django 4.0.1 on 2024-08-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sno', models.IntegerField()),
                ('Sname', models.CharField(max_length=24)),
                ('Sage', models.IntegerField()),
                ('Scourse', models.CharField(max_length=54)),
            ],
        ),
    ]
